[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tirehtoori.test_settings"

[tool.ruff]
target-version = "py311"
lint.select = [
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # pycodestyle
    "E",
    "W",
    # flake8-bandit
    "S",
    # flake8-boolean-trap
    "FBT",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # flake8-django
    "DJ",
    # flake8-gettext
    "INT",
    # flake8-pie
    "PIE",
    # flake8-print
    "T20",
    # flake8-simplify
    "SIM",
    # pep8-naming
    "N",
    # pygrep-hooks
    "PGH",
    # isort
    "I001"
]
lint.extend-per-file-ignores = { "*/migrations/*" = ["E501"], "*/tests/*" = ["E501", "S101"] }
