# Generated by Django 5.1.1 on 2024-09-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirect", "0002_redirectrule_pass_query_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirectrule",
            name="append_subpath",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the subpath will be appended to the destination "
                "URL. For example, /foo/bar will redirect to the destination "
                'URL + /bar. Does nothing if "Match subpaths" is not '
                "checked.",
                verbose_name="Append subpath",
            ),
        ),
        migrations.AddField(
            model_name="redirectrule",
            name="match_subpaths",
            field=models.BooleanField(
                default=False,
                help_text="If checked, requests to subpaths will also be redirected. "
                "For example, /foo/bar will redirect to the same destination "
                "as /foo. In case of conflict, the most specific rule will "
                "be used.",
                verbose_name="Match subpaths",
            ),
        ),
    ]
