# Generated by Django 5.1.1 on 2024-10-17 06:50

import django.db.models.deletion
from django.db import migrations, models


def migrate_domain_to_domain_name(apps, schema_editor):
    Domain = apps.get_model("redirect", "Domain")
    DomainName = apps.get_model("redirect", "DomainName")

    for domain in Domain.objects.all():
        DomainName.objects.create(name=domain.name, domain=domain)


class Migration(migrations.Migration):
    dependencies = [
        ("redirect", "0003_redirectrule_append_subpath_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The domain name to redirect from. Do not include "
                        'the protocol or path. E.g. "example.com"',
                        max_length=255,
                        unique=True,
                        verbose_name="Domain name",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="redirect.domain",
                        verbose_name="Domain",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(migrate_domain_to_domain_name),
        # RenameField and AlterField for Domain were added manually;
        # the generated migration had RemoveField + AddField instead.
        migrations.RenameField(
            model_name="domain",
            old_name="name",
            new_name="display_name",
        ),
        migrations.AlterField(
            model_name="domain",
            name="display_name",
            field=models.CharField(
                help_text="Display name for the domain. For informational purposes "
                "only.",
                max_length=255,
                unique=True,
                verbose_name="Display name",
            ),
        ),
    ]
