name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-django-api.yml@main
    secrets: inherit
    with:
      python-version: 3.11
      postgres-major-version: 14
      extra-commands: |
        echo "ENABLE_ADMIN_APP=true" >> $GITHUB_ENV
        echo "ENABLE_REDIRECT_APP=true" >> $GITHUB_ENV
